### ISSUE TITLE
"400" Bad Request when update from admin panel (CLI works)

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/netdata_ynh#105] opened 2023-03-03 16:09 UTC
Yunohost 11.1.12.2 (stable)
VPS Hetzner CX 31 (8Go RAM 2 vCPU intel)
Interface admin + SSH

When i try to update NetData (netdata) from 1.37.1-ynh1 to 1.38.1-ynh1 I have this error message : 
```
Erreur: "400" Bad Request

Action: "PUT" /yunohost/api/apps/netdata/upgrade

Message d'erreur :
I don't understand you... 
```

**Only CLI works** 

![image](https://user-images.githubusercontent.com/60814449/222769581-6a2fda6e-c22e-4dac-97e6-b74c525da51f.png)

**Comment by isAAAc** [comment] 2023-03-03 16:23
same here yesterday

**- workaround:** 
no data to keep really on my side, i reinstalled the app

**Comment by brimwats** [comment] 2023-03-07 22:02
Confirming that I am also receiving this error.

**Comment by joss-rendall** [comment] 2023-03-18 09:30
Also Here !!

**Comment by inrepublica** [comment] 2023-04-15 11:25
Same here

**Comment by JimboJoe** [comment] 2023-04-30 07:55
Duplicate of #94; Current workaround is to upgrade via CLI.

**Closed** 2023-04-30 07:54 UTC
